service: publicera-${self:custom.path}-service

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1
  profile: smokingdots
  environment:
    db_url: mongodb://admin:password123@ds159185.mlab.com:59185
    db_name: publicera

custom:
  path: user

functions:
  getUser:
    handler: functions/handler.getUser
    events:
      - schedule: rate(2 minutes)
      - http:
          path: ${self:custom.path}/get/{id}
          method: get

  updateUser:
    handler: functions/handler.updateUser
    events:
      - schedule: rate(2 minutes)
      - http:
          path: ${self:custom.path}/update/{id}
          method: post

  createUser:
    handler: functions/handler.createUser
    events:
      - schedule: rate(2 minutes)
      - http:
          path: ${self:custom.path}/create
          method: post
